<?php

namespace Techmaki\Bundle\HackboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantRepository extends EntityRepository
{
}